CREATE DATABASE IF NOT EXISTS movies;
SHOW DATABASES;

USE movies;

CREATE TABLE IF NOT EXISTS movies (
	mID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30),
    year INT,
    director VARCHAR(50)
);

SHOW TABLES;

CREATE TABLE IF NOT EXISTS reviewer (
	rID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50)
);

SHOW TABLES;

CREATE TABLE IF NOT EXISTS rating (
	rID INT PRIMARY KEY,
	mID INT,
    stars TINYINT,
    ratingDate DATE,
	FOREIGN KEY (rID) REFERENCES reviewer(rID),
    FOREIGN KEY (mID) REFERENCES movies(mID)
);

